name: CI & Deploy to OCI

on:
  push:
    branches: [ main ]          # deploy only from main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dummy test
        run: echo "tests passed"

deploy:
  needs: test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        # (SSH_USER and SERVER_IP stay in secrets)

    - name: Pull latest code, install deps, restart
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} <<'EOF'
          set -e
          cd ~/TIRP
          git pull --ff-only
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flaskapp
        EOF
