name: CI & Deploy to OCI

on:
  push:
    branches: [ main ]          # deploy only from main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dummy test
        run: echo "tests passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # install rsync on the runner
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      # load SSH key and host fingerprint
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # sync repo to OCI VM
      - name: Sync code to server
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=yes" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/TIRP/

      # install deps & restart Flask service
      - name: Install deps and restart service
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} <<'EOF'
            set -e
            cd ~/TIRP
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp
          EOF
