name: CI & Deploy to OCI

on:
  push:
    branches: [ main ]          # change if your prod branch is different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (optional) add pytest or flake8 here
      - name: Dummy test
        run: echo "tests passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Install rsync            # ← NEW
      run: sudo apt-get update && sudo apt-get install -y rsync

      # 1️⃣  Load the SSH key & host fingerprint
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # 2️⃣  Sync the repo to the VM (fast incremental)
      - name: Rsync code to server
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=yes" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/TIRP/

      # 3️⃣  Install any new deps and restart the service
      - name: Install deps & restart service
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} <<'EOF'
            set -e
            cd ~/TIRP
            # activate venv
            source venv/bin/activate
            # install updated requirements
            pip install -r requirements.txt
            # restart systemd service
            sudo systemctl restart flaskapp
          EOF